### ISSUE TITLE
EPIC: Repository and agile tool

### ISSUE THREAD

**Issue by queenisabaer** [queenisabaer/friendventure#1]
**Description:**
- Set up GitHub Repositories for frontend and backend part including the agile tool GitHub Projects.
---
**Related User Stories:**
- [x] [Set up GitHub Repository for front end](https://github.com/queenisabaer/friendventure/issues/2)
- [x] [Set up GitHub Repository for api](https://github.com/queenisabaer/friendventure/issues/3)
- [x] [Add project to repository](https://github.com/queenisabaer/friendventure/issues/4)
