### ISSUE TITLE
USER STORY: View profile

### ISSUE THREAD

**Issue by queenisabaer** [queenisabaer/friendventure#10]
As a **logged-in user**, I want **to view my profile and the profiles of other users** so that **I can see profile information, their friendventures, and updates**.

---
**Acceptance criteria:**

- Users can access a profile page that displays personal information, profile picture, recent friendventures.
- Users can see other users profile page

---
**Tasks:**

- [x] Create profile page
- [x] Use the API to get profile information.
- [x] Provide profile information on profile page

---
**EPIC:**
[Profile Management](https://github.com/queenisabaer/friendventure/issues/9)
