### ISSUE TITLE
USER STORY: Follow/unfollow a profile

### ISSUE THREAD

**Issue by queenisabaer** [queenisabaer/friendventure#12]
As a **logged-in user** I can **follow or unfollow another user** so that **can see their updates and FriendVentures in my feed**

---
**Acceptance criteria:**

- Users can follow other profiles by clicking a "Follow" button.
- Users can see how many people they follow.
- The number of followers is updated.
- Following/Unfollowing a profile adds/removes the user's updates to the follower's feed.

---
**Tasks:**

- [x] Create functionality to follow another user
- [x] Create functionality to unfollow a user
- [x] Update the follower count and the content depending on the following status

---
**EPIC:**
[Profile Management](https://github.com/queenisabaer/friendventure/issues/9)
