### ISSUE TITLE
EPIC: FriendVenture Creation

### ISSUE THREAD

**Issue by queenisabaer** [queenisabaer/friendventure#13]
**Description:**
Enable users to create, edit, and delete FriendVentures, providing essential event details to invite friends for activities.

---
**Related User Stories:**

- [ ] [Create a FriendVenture](https://github.com/queenisabaer/friendventure/issues/14)
- [ ] [Edit a FriendVenture](https://github.com/queenisabaer/friendventure/issues/15)
- [ ] [Delete a FriendVenture](https://github.com/queenisabaer/friendventure/issues/16)
