### ISSUE TITLE
USER STORY: Delete a FriendVenture

### ISSUE THREAD

**Issue by queenisabaer** [queenisabaer/friendventure#16]
As a **logged-in user** I can **delete my existing FriendVenture** so that **I can remove it if the event is cancelled**

---
**Acceptance criteria:**

- The user must be logged in to delete a FriendVenture.
- The user can only delete FriendVenture they have created.
- The FriendVenture should be removed from the database and no longer accessible.

---
**Tasks:**

- [ ] Implement the delete functionality.
- [ ] Develop backend logic to remove the FriendVenture from the database.
- [ ] Implement unit and integration tests.

---
**EPIC:**
[FriendVenture Creation](https://github.com/queenisabaer/friendventure/issues/13)
