### ISSUE TITLE
EPIC: Engage with a FriendVenture

### ISSUE THREAD

**Issue by queenisabaer** [queenisabaer/friendventure#17]
**Description:**

Allow users:
- to comment and rate on a FriendVenture, facilitating communication and discussion about the events
- to mark their participation in FriendVentures, indicating their attendance to other users.
- to remember FriendVentures, making it easy to revisit and track events they are interested in

---
**Related User Stories:**

- [x] [Comment on a FriendVenture](https://github.com/queenisabaer/friendventure/issues/18)
- [x] [Participate in a FriendVenture](https://github.com/queenisabaer/friendventure/issues/20)
- [ ] [Rate a FriendVenture](https://github.com/queenisabaer/friendventure/issues/19)
- [x] [Remember a FriendVenture](https://github.com/queenisabaer/friendventure/issues/21)
- [ ] [Like a Comment](https://github.com/queenisabaer/friendventure/issues/22)
