### ISSUE TITLE
USER STORY: Rate a FriendVenture

### ISSUE THREAD

**Issue by queenisabaer** [queenisabaer/friendventure#19]
As a **logged-in user** I can **rate a FriendVenture** so that **I can show the creator of the event and other users how the event was**

---
**Acceptance criteria:**

- The user must be logged in to comment.
- The rating should be associated with the user and the friendventure
- The rating should be saved to the database and displayed on the friendventure page.

---
**Tasks:**

- [ ] Design the rating form.
- [ ] Develop backend logic to save the rating to the database.
- [ ] Implement unit and integration tests.

---
**EPIC:**
[Commenting on FriendVentures](https://github.com/queenisabaer/friendventure/issues/17)
