### ISSUE TITLE
USER STORY: Participate in a FriendVenture

### ISSUE THREAD

**Issue by queenisabaer** [queenisabaer/friendventure#20]
As a **logged-in user** I can **mark myself as participating in a FriendVenture** so that **others know I will be attending**

---
**Acceptance criteria:**

- The user must be logged in to participate.
- Participation should be saved to the database and associated with the user and FriendVenture.
- The user should be able to unmark their participation if they change their mind.

---
**Tasks:**

- [x] Design the participation toggle.
- [x] Develop backend logic to save and remove participation.
- [ ] Implement unit and integration tests.

---
**EPIC:**
[Engage with a FriendVenture](https://github.com/queenisabaer/friendventure/issues/17)
