### ISSUE TITLE
USER STORY: Bookmark a FriendVenture

### ISSUE THREAD

**Issue by queenisabaer** [queenisabaer/friendventure#21]
As a **logged-in user** I can **bookmark a FriendVenture to remember** so that **I can easily find it later**

---
**Acceptance criteria:**

- The user must be logged in to bookmark a FriendVenture.
- A bookmarked FriendVentures should be saved to the database and associated with the user.
- The user should be able to unmark a bookmarked FriendVenture.

---
**Tasks:**

- [x] Design the remember functionality.
- [x] Develop backend logic to save and remove remembered FriendVentures.
- [ ] Implement unit and integration tests.

---
**EPIC:**
[Engage with a FriendVenture](https://github.com/queenisabaer/friendventure/issues/17)
