### ISSUE TITLE
USER STORY: Like a Comment

### ISSUE THREAD

**Issue by queenisabaer** [queenisabaer/friendventure#22]
As a **logged-in user** I can **like a comment on a FriendVenture** so that **I can show my appreciation for valuable comments**

---
**Acceptance criteria:**

- The user must be logged in to like a comment.
- A user can like a comment only once, and the same user can unlike the comment.
- The like should be saved to the database and the total like count should be updated and displayed on the comment.

---

**Tasks:**

- [ ] Design the like button UI for comments.
- [ ] Implement the backend logic to save and remove likes from the database.
- [ ] Develop a method to count and display the number of likes per comment.
- [ ] Implement unit and integration tests.

---
**EPIC:**
[Engage with a FriendVenture](https://github.com/queenisabaer/friendventure/issues/17)
