### ISSUE TITLE
EPIC: Testing

### ISSUE THREAD

**Issue by queenisabaer** [queenisabaer/friendventure#23]
**Description:**

Before submission, test the code before submission.

---
**Related User Stories:**

- [x] [Python Testing](https://github.com/queenisabaer/friendventure/issues/24)
- [x] [JavaScript Testing](https://github.com/queenisabaer/friendventure/issues/25)
- [x] [Develop manual test cases](https://github.com/queenisabaer/friendventure/issues/26)
