### ISSUE TITLE
EPIC: Validation

### ISSUE THREAD

**Issue by queenisabaer** [queenisabaer/friendventure#27]
**Description:**
Validate the code before submission

---
**Related User Stories:**

- [x] [CSS Validation](url)
- [x] [JavaScript Validation](url)
- [x] [Pep8 Validation](url)
