### ISSUE TITLE
USER STORY: API - Profiles

### ISSUE THREAD

**Issue by queenisabaer** [queenisabaer/friendventure#32]
As a *superuser* I can *see a list of all profiles* so that *I can see all profiles that have been set up*.
As a *superuser* I can *see details of a profile* so that *I can see a person's profile data*.
As a *developer*, I can *automatically create a user profile when a new user signs up for my application* so that *the user has a profile ready for them upon registration.*

---
**Acceptance criteria:**

- Profile with fields such as name, description, profile image, phone number, and email
- Profile List view
- Profile is auto-created through signals when a new user signs up

---
**Tasks:**

- [x] Create Profile model with required fields.
- [x] Create serializer for Profile model.
- [x] Create view to handle profile creation.
- [x] Add URL routing for profile creation endpoint.
- [x] Write tests for profile creation.

---
**EPIC:**

[API - Basic Profile Management](https://github.com/queenisabaer/friendventure/issues/33)
