### ISSUE TITLE
USER STORY: API - FriendVenture

### ISSUE THREAD

**Issue by queenisabaer** [queenisabaer/friendventure#35]
As a *superuser* I can *see a list of all FriendVentures* so that *I can see all FriendVentures that have been set up.*
As a *superuser* I can *seethe details of a FriendVenture* so that *I can see all information about a specific FriendVentures.*
As a *superuser* I can *filter FriendVentures by category* so that *I can see only the FriendVentures associated with a specific category.*

---
**Acceptance criteria:**

- Friendventure with fields such as title, image, date, time, place, description, and category
- Friendventure list and detail view

---
**Tasks:**

- [x]  Create Friendventure model with required fields.
- [x]  Create serializer for Friendventure model.
- [x]  Create view to handle friendventure creation.
- [x]  Add filter to the friendventures view
- [x]  Add URL routing for friendventure creation endpoint.
- [x]  Write tests for friendventure creation.

---
**EPIC:**

[API - Basic Profile Management](https://github.com/queenisabaer/friendventure/issues/33)
