### ISSUE TITLE
USER STORY: API - Comments

### ISSUE THREAD

**Issue by queenisabaer** [queenisabaer/friendventure#36]
As a *superuser* I can *see a list of all comments related to a FriendVenture* so that *I can see all comments that have been created for a friendventure by id.*

---
**Acceptance criteria:**

- Comment with fields such as friendventure, and content
- Comment list view

---
**Tasks:**

- [x] Create Comment model with required fields.
- [x] Create serializer for Comment model.
- [x] Create view to handle comment creation.
- [x] Add URL routing for comment creation endpoint.
- [x] Write tests for comment creation.

---
**EPIC:**

[API - Social Interactions](https://github.com/queenisabaer/friendventure/issues/34)
