### ISSUE TITLE
USER STORY: API - Followers

### ISSUE THREAD

**Issue by queenisabaer** [queenisabaer/friendventure#37]
As a *superuser* I can *create a follow to another user* so that *I can follow other users*

---
**Acceptance criteria:**

- Follower with fields such as follower, and followee
- Follower list view
- Following is only allowed for authenticated users.
- User cannot follow the same user more than once.

---
**Tasks:**

- [x] Create Follower model with required fields.
- [x] Create serializer for Follower model.
- [x] Create view to handle following another user.
- [x] Add URL routing for following another user endpoint.
- [x] Write tests for following another user.

---
**EPIC:**
[API - Social Interactions](https://github.com/queenisabaer/friendventure/issues/34)
