### ISSUE TITLE
USER STORY: API - Participants

### ISSUE THREAD

**Issue by queenisabaer** [queenisabaer/friendventure#38]
As a *superuser*, I can *view a list of all participants in a FriendVenture* so that *I can track who is joining each activity*
As a *superuser,* I can *view the participation details for a specific FriendVenture* so that *I can see which users are involved in that particular activity.*

---
**Acceptance criteria:**

- Participant with fields such as friendventure, comment and user
- Participant list view
- Participating is only allowed for authenticated users.

---
**Tasks:**

- [x] Create Participant model with required fields.
- [x] Create serializer for Participate model.
- [x] Create view to handle participating in a FriendVenture.
- [x] Add URL routing for participating in a FriendVenture endpoint.
- [x] Write tests for participating in a FriendVenture.

---
**EPIC:**

[API - Social Interactions](https://github.com/queenisabaer/friendventure/issues/34)
