### ISSUE TITLE
USER STORY: API- Bookmarks

### ISSUE THREAD

**Issue by queenisabaer** [queenisabaer/friendventure#39]
As a *superuser*, I can *view all FriendVentures that users have added to their bookmarks lists* so that *I can see which activities users are interested in revisiting.*
As a *superuser,* I can *view details of specific FriendVentures in a user’s bookmarks list* so that *I can understand user interests and preferences.*

---
**Acceptance criteria:**

- Bookmark with fields such as friendventure, and user
- Bookmark list view
- Bookmarking is only allowed for authenticated users.
- User cannot bookmark the same friendventure more than once.

---
**Tasks:**

- [x] Create Bookmark model with required fields.
- [x] Create serializer for Bookmark model.
- [x] Create view to handle adding a friendventure to bookmark list.
- [x] Add URL routing for adding a friendventure to bookmark list endpoint.
- [x] Write tests for adding a friendventure to bookmark list.

---
**EPIC:**
[API - Social Interactions](https://github.com/queenisabaer/friendventure/issues/34)
