### ISSUE TITLE
EPIC: User Registration and Authentication

### ISSUE THREAD

**Issue by queenisabaer** [queenisabaer/friendventure#5]
**Description:**

Implement user registration and login functionality

---
**Related User Stories:**

- [x] [User Registration](https://github.com/queenisabaer/friendventure/issues/6)
- [ ] [User Login](https://github.com/queenisabaer/friendventure/issues/7)
- [x] [User Logout](https://github.com/queenisabaer/friendventure/issues/8)
