### ISSUE TITLE
USER STORY: User log out

### ISSUE THREAD

**Issue by queenisabaer** [queenisabaer/friendventure#8]
As a **logged-in user** I am able **to log out** so that **I can keep my account secure.**

---
**Acceptance criteria:**

- When I press _Log out_ in the navigation bar, I am logged out and returned to the landing page. 
- The navigation bar changes to the view for logged-out users.

---
**Tasks:**

- [x] Create a logout functionality.
- [x] The items displayed on the navigation bar alter based on the user's current status (whether logged in or logged out)
- [x] When the user successfully logs out, they are redirected to the logged out view of the home page

---
**EPIC:**
[User Registration and Authentication](https://github.com/queenisabaer/friendventure/issues/5)
