### ISSUE TITLE
EPIC: Profile Management

### ISSUE THREAD

**Issue by queenisabaer** [queenisabaer/friendventure#9]
**Description:**
Encompasses the essential features and functionalities that allow users to interact with and manage their profiles within the application.

---
**Related User Stories:**

- [x] [View profile](https://github.com/queenisabaer/friendventure/issues/10)
- [x] [Edit profile](https://github.com/queenisabaer/friendventure/issues/11)
- [ ] [Follow/Unfollow a profile](https://github.com/queenisabaer/friendventure/issues/12)
